### ISSUE TITLE
Should allow for removal of SSH keys

### ISSUE THREAD

**Issue by wwentland** [saltstack-formulas/reverse-users-formula#5]
If one uses this formula one has to maintain a separate state to manage SSH keys that should be removed. The users-formula allows for removal of SSH keys and if would be nice if one could use the following in the reverse users formula:

```
users:
[...]
  # Example with ssh keys, overrides, and absent
  user.b:
    # Data in userinfo gets applied to all matching minions
    userinfo:
      - public-keys:
        - salt://users/ssh-keys/user.b-pc1.pub
      - absent-public-keys:
        - salt://users/ssh-keys/user.b-pc0.pub
[...]
    present:
      G@id:example1.com:
        # Remove user.b-pc42.pub key from example1.com
        - absent-public-keys:
          - salt://users/ssh-keys/user.b-pc42.pub
[...]
```

This should, unsurprisingly, generate suitable `auth_ssh.absent` states for that user.
